// <auto-generated />
using JobPlatform.DAL.Context;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace JobPlatform.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260601020000_AddApplicationNotes")]
    partial class AddApplicationNotes
    {
    }
}
